import { getArticleById, getAllArticles } from "../../../lib/articles";
import { notFound } from "next/navigation";
import Link from "next/link";
import styles from "./article.module.css";
import MermaidInit from "../../../components/MermaidInit";

// Generate static parameters for build time
export function generateStaticParams() {
  const articles = getAllArticles(true); // Include drafts so they are built but hidden
  return articles.map((article) => ({
    id: article.id,
  }));
}

export default async function ArticlePage({ params }: { params: Promise<{ id: string }> }) {
  const resolvedParams = await params;
  const article = getArticleById(resolvedParams.id);

  if (!article) {
    notFound();
  }

  return (
    <div className="container" style={{ maxWidth: "800px", padding: "40px 20px" }}>
      <Link href="/" style={{ color: "var(--brand-primary)", fontWeight: "bold", display: "inline-block", marginBottom: "20px" }}>
        ← トップページに戻る
      </Link>
      
      <article className="card" style={{ padding: "40px" }}>
        <div style={{ marginBottom: "20px" }}>
          <span className="badge">{article.category}</span>
          {article.draft && <span className="badge" style={{ background: "#fee2e2", color: "#ef4444", marginLeft: "10px", borderColor: "#fca5a5" }}>下書き (Draft)</span>}
        </div>
        
        <h1 style={{ fontSize: "2.2rem", marginBottom: "20px", lineHeight: 1.3 }}>{article.title}</h1>
        
        <div style={{ display: "flex", justifyContent: "space-between", color: "var(--text-light)", fontSize: "0.9rem", borderBottom: "1px solid var(--border-light)", paddingBottom: "20px", marginBottom: "30px" }}>
          <span>Source: <a href={article.source_url} target="_blank" rel="noopener noreferrer" style={{ textDecoration: "underline" }}>{article.source_name}</a></span>
          <span>{new Date(article.date).toLocaleDateString('ja-JP')}</span>
        </div>

        {/* This div renders the actual HTML generated by Dify! */}
        <MermaidInit />
        <div 
          className={styles.articleContent}
          dangerouslySetInnerHTML={{ __html: article.content }} 
        />
      </article>
    </div>
  );
}
